# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md"]
paginate: 5
paginate_path: ":num"
sass:
    style: :compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap

# Custom Variables
analytics: "UA-72054920-1"
author:
  email: "&#109;&#97;&#98;&#101;&#114;&#103;&#101;&#114;&#54;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
  github: "mark-berger"
  linkedin: "maberger"
  name: "Mark Berger"
  uri: "http://maberger.com"
description: "Personal website of Mark Berger, BASc Computer Engineering."
name: "Mark Berger"
title: "Mark Berger"
url: "http://maberger.com"