# Jekyll Settings
excerpt_separator: <!--more-->
exclude: ["CNAME", "README.md"]
paginate: 3
paginate_path: ":num"
sass:
    style: :compressed

# Custom Variables
title: "Mark Berger"
url: "http://maberger.com"
description: "Personal website for Mark Berger."
contact:
  email: "&#109;&#97;&#98;&#101;&#114;&#103;&#101;&#114;&#54;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
  linkedin: "maberger"
  github: "mark-berger"